// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clientes.gateways.dbcontext;

namespace clientes.gateways.Migrations
{
    [DbContext(typeof(ClientesDbContext))]
    [Migration("20190626173342_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("clientes.gateways.model.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("clientes.gateways.model.EnderecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<string>("Cidade");

                    b.Property<int?>("ClienteModelId");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Numero");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteModelId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("clientes.gateways.model.EnderecoModel", b =>
                {
                    b.HasOne("clientes.gateways.model.ClienteModel")
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
